name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: List pip cache before pip install
      run: |
        bash -c 'find ~/.cache/pip -type f || true'
    - name: Lint with flake8
      run: |
        python3 -m pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --show-source --statistics
    - name: install genelocator
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: List pip cache after pip install
      run: |
        find ~/.cache/pip -type f
